# Generated by Django 3.1.5 on 2021-01-30 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Имя(логин) пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('permissions', models.CharField(max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=0)),
                ('is_active', models.BooleanField(default=1)),
                ('is_superuser', models.BooleanField(default=0)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Дата последнего посещения')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('date_activated', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации профиля')),
                ('skill', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('count_vote', models.PositiveIntegerField(default=0)),
                ('activate_key', models.CharField(default='NULL', max_length=32, null=True)),
                ('inviter', models.CharField(default='NULL', max_length=10, null=True)),
                ('profile_sex', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=10)),
                ('profile_country', models.CharField(default='NULL', max_length=30, null=True)),
                ('profile_region', models.CharField(default='NULL', max_length=30, null=True)),
                ('profile_city', models.CharField(default='NULL', max_length=30, null=True)),
                ('profile_birthday', models.DateField(blank=True, default=None, null=True)),
                ('profile_about', models.TextField(default='NULL', null=True)),
                ('profile_avatar', models.ImageField(max_length=250, null=True, upload_to='uploads/images/%Y/%m/%d/')),
                ('settings_notice_new_topic', models.BooleanField(default=1)),
                ('settings_notice_new_comment', models.BooleanField(default=1)),
                ('settings_notice_new_message', models.BooleanField(default=1)),
                ('settings_notice_reply_comment', models.BooleanField(default=1)),
                ('settings_notice_new_comment_to_topic', models.BooleanField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название блога')),
                ('description', models.TextField(null=True, verbose_name='Описание блога')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('avatar', models.ImageField(max_length=250, null=True, upload_to='uploads/images/%Y/%m/%d/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название поста')),
                ('tags', models.CharField(default='', max_length=250, verbose_name='Список тегов(разделять запятой)')),
                ('hashtag', models.CharField(default='', max_length=50)),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('author_ip', models.GenericIPAddressField()),
                ('is_published', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('readings', models.PositiveIntegerField(default=0, verbose_name='Количество дочитываний')),
                ('votes_plus', models.PositiveIntegerField(default=0, verbose_name='Количество положительных голосов')),
                ('votes_minus', models.PositiveIntegerField(default=0, verbose_name='Количество отрицательных голосов')),
                ('comments_total', models.PositiveIntegerField(default=0, verbose_name='Количество комментариев')),
                ('text', models.TextField(verbose_name='Содержимое топика')),
                ('text_short', models.TextField(verbose_name='Краткое содержимое для превью')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Имя автора')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Топик',
                'verbose_name_plural': 'Топики',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(null=True)),
                ('target_id', models.PositiveIntegerField()),
                ('target_type', models.CharField(choices=[('topic', 'Комментарий к топику'), ('talk', 'Личное сообщение')], max_length=10)),
                ('target_blog_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('last_editor_id', models.PositiveIntegerField(null=True)),
                ('author_ip', models.GenericIPAddressField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('votes_plus', models.PositiveIntegerField(default=0, verbose_name='Количество положительных голосов')),
                ('votes_minus', models.PositiveIntegerField(default=0, verbose_name='Количество отрицательных голосов')),
                ('is_published', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
