# Generated by Django 3.1.5 on 2021-02-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210212_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccontent',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topic_texts', serialize=False, to='blogs.topic', verbose_name='Топик'),
        ),
    ]
